spring:
  profiles:
    active: docker

  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG