
spring:
  profiles:
    active: docker

server:
    port: 8080
    error:
      include-message:: always

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080

logging:
  level:
    root: INFO
    se.magnus: DEBUG
