spring:
  profiles:
    active: docker

    jpa:
      hibernate:
        ddl-auto: update

    datasource:
      url: jdbc:mysql://mysql/review-db
      username: root
      password: 12345678
      hikari:
        initializationFailTimeout: 60000


server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    root: INFO
    se.magnus.microservices: DEBUG