spring:
  profiles:
    active: docker

    mongodb:
      embedded:
        version: 3.5.5

    data:
      mongodb:
        host: localhost
        port: 27017
        database: product-db


server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG